### ISSUE TITLE
Invoice download for manager user should not lead to 403 error

### ISSUE THREAD

**Issue by Deele** [WebMultishopCompany/tgx#1]
To reproduce:

1. Open /en/mgmt/invoices
2. Login as manager
3. Open any specific invoice
4. Click "Download invoice" button

Expected behavior:

You see PDF view (if chrome that opens PDF in window) or file download prompt.

Current behavior:

You see "403 - Forbidden" error

**Comment by teamgurux** [comment]
we need this one repaired. Its creating us problems

**Comment by teamgurux** [comment]
its in section https://www.teamgurux.com/en/mgmt/invoices

**Comment by Deele** [comment]
Done
