### ISSUE TITLE
Enhance providers list widget with clickable provider names

### ISSUE THREAD

**Issue by teamgurux** [WebMultishopCompany/tgx#5]
In the guru list have the name of the guru(of profile) clicable to the full profile

**Comment by Deele** [comment]
@teamgurux Are you talking about this one?

![snap 2018-07-04 at 16 53 02](https://user-images.githubusercontent.com/477326/42280969-e8677f12-7faa-11e8-85ba-98f3d428367b.jpg)

**Comment by teamgurux** [comment]
Yes. its should be the blue color that we use the button

**Comment by teamgurux** [comment]
Yes. its should be the blue color that we use the button

**Comment by Deele** [comment]
Did you purposefully close this issue?

**Comment by teamgurux** [comment]
No, it was by mistake. It said Close and Comment. And i thought it was to
leave the comment and close the window. i have reopen it.

**Comment by Deele** [comment]
Done
