### ISSUE TITLE
Opening existing invoice view page should not lead to 404 error

### ISSUE THREAD

**Issue by teamgurux** [WebMultishopCompany/tgx#54]
In the manager's dashboard when we go to the transaction and we press actions for 1 order it goes to error. So now we can not put that it was paid to Guru.
https://www.teamgurux.com/en/mgmt/transactions

also the same problem in invoices page
https://www.teamgurux.com/en/mgmt/invoices

**Comment by teamgurux** [comment]
This page is working when i press actions
https://www.teamgurux.com/en/mgmt/invoices

This one is still not working
https://www.teamgurux.com/en/mgmt/transactions

**Comment by Deele** [comment]
Done

**Comment by teamgurux** [comment]
Please check it again. Its not working in DEV of Production

**Comment by teamgurux** [comment]
dev or production*

**Comment by Deele** [comment]
@teamgurux It is currently in dev. I will push everything for this version everything at once when this milestone is done
