### ISSUE TITLE
TRANSACTION AMOUNTS ARE WRONG

### ISSUE THREAD

**Issue by teamgurux** [WebMultishopCompany/tgx#55]
we have a huge problem in the commission fees. Somehow you are counting for the bank comission fee 2 times. And the amounts appearing in our transaction panel are wrong. This needs to be fixed ASAP.

Check the following scenario:

ORDER P002X0039

16Eur for service at 10%fee 
2Eur for extras at 0% fee
TGX should recieve 1.6Eur and Guru 18Eur-1.6Eur= 16.4Eur

Total Paid by client: 18.40Eur (including bank fee)

We have received in bank 18.03Eur (after bank already removed its fee. Something is wrong with our multiplier, check if its 2.0041) 

IN OUR TRANSACTION PANEL APPEARS:

Order amount 18.00Eur (correct)

provider share: 16.00Eur (wrong amount. it should be 16.40Eur)

Invoiced(products/proc.commiss):  2Eur (1.60 / 0.40Eur)   (this is correct. But the problem is that you do this counts from the order amount, and you should do it from the amount paid by client. Thats why we are charging 0.40cent 2 times)

PLEASE CHECK THIS ASAP. WE ARE LEGALY IN TROUBLE IF THIS DOESNT HIT THE RIGHT AMOUNTS

**Comment by Deele** [comment]
Table values updated, processing commission multiplier changed from `0.022` to `0.0200408`. Done.
